### ISSUE TITLE
OMF Test File Can not be loaded

### ISSUE THREAD

**Issue by Terranigmus** [OpenGeoVis/omfvista#1]
The OMF test file can not be loaded and results in 

```
Traceback (most recent call last):

  File "<ipython-input-37-1d8fccc63af4>", line 1, in <module>
    proj2=omfvtk.load_project('test_file.omf')

  File "C:\Users\Paul\Anaconda3\lib\site-packages\omfvtk\wrapper.py", line 122, in load_project
    reader = omf.OMFReader(filename)

  File "C:\Users\Paul\Anaconda3\lib\site-packages\omf\fileio.py", line 107, in __init__
    self._uid, self._json_start = self.read_header()

  File "C:\Users\Paul\Anaconda3\lib\site-packages\omf\fileio.py", line 155, in read_header
    raise ValueError('Invalid OMF file')

ValueError: Invalid OMF file
```

**Comment by Terranigmus** [comment]
I took the one from the OMF 1.0 repository, sorry, should have said that!
